name: Install AMPL

on: 
  workflow_dispatch:

jobs:
  setup-ampl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AMPL
        run: |
          wget -O 'ampl.linux64.tgz' https://portal.ampl.com/external/?url=https://portal.ampl.com/dl/amplce/ampl.linux64.tgz
          tar -xzf ampl.linux64.tgz
          export PATH=$PWD/ampl.linux-intel64/ampl:$PATH

      - name: Verify Installation
        run: |
          pwd
          cd ampl.linux-intel64
          ./ampl --version
      - name: run the file
        run: |
          pwd
          cd ampl.linux-intel64
          ./ampl model ../qF.mod
